export const storeData = [
    {
        id: 1,
        section: "قهرمان",
        totalCustomers: 0,
        lastPurchase: 0,
        numberOfPurchases: 500,
        purchaseAmount: 0,
    },
    {
        id: 2,
        section: "قهرمان",
        totalCustomers: 0,
        lastPurchase: 0,
        numberOfPurchases: 500,
        purchaseAmount: 0,
    },
    {
        id: 3,
        section: "قهرمان",
        totalCustomers: 0,
        lastPurchase: 0,
        numberOfPurchases: 500,
        purchaseAmount: 0,
    },
    {
        id: 4,
        section: "قهرمان",
        totalCustomers: 0,
        lastPurchase: 0,
        numberOfPurchases: 500,
        purchaseAmount: 0,
    },
    {
        id: 5,
        section: "قهرمان",
        totalCustomers: 0,
        lastPurchase: 0,
        numberOfPurchases: 500,
        purchaseAmount: 0,
    },
    {
        id: 6,
        section: "قهرمان",
        totalCustomers: 0,
        lastPurchase: 0,
        numberOfPurchases: 500,
        purchaseAmount: 0,
    },
    {
        id: 7,
        section: "قهرمان",
        totalCustomers: 0,
        lastPurchase: 0,
        numberOfPurchases: 500,
        purchaseAmount: 0,
    },
    {
        id: 8,
        section: "قهرمان",
        totalCustomers: 0,
        lastPurchase: 0,
        numberOfPurchases: 500,
        purchaseAmount: 0,
    },
    {
        id: 9,
        section: "قهرمان",
        totalCustomers: 0,
        lastPurchase: 0,
        numberOfPurchases: 500,
        purchaseAmount: 0,
    },
    {
        id: 10,
        section: "قهرمان",
        totalCustomers: 0,
        lastPurchase: 0,
        numberOfPurchases: 500,
        purchaseAmount: 0,
    },
    {
        id: 11,
        section: "قهرمان",
        totalCustomers: 0,
        lastPurchase: 0,
        numberOfPurchases: 500,
        purchaseAmount: 0,
    },
    {
        id: 12,
        section: "قهرمان",
        totalCustomers: 0,
        lastPurchase: 0,
        numberOfPurchases: 500,
        purchaseAmount: 0,
    },
];
