export const storeData = [
    {
        id: 1,
        section: "قهرمان",
        totalCustomers: 0,
        lastPurchase: 0,
        numberOfPurchases: 4000,
        purchaseAmount: 0,
    },
    {
        id: 2,
        section: "وفادار",
        totalCustomers: 0,
        lastPurchase: 0,
        numberOfPurchases: 500,
        purchaseAmount: 0,
    },
    {
        id: 3,
        section: "به سوی وفاداری",
        totalCustomers: 0,
        lastPurchase: 0,
        numberOfPurchases: 350,
        purchaseAmount: 0,
    },
    {
        id: 4,
        section: "تازه وارد",
        totalCustomers: 0,
        lastPurchase: 0,
        numberOfPurchases: 6000,
        purchaseAmount: 0,
    },
    {
        id: 5,
        section: "امیدوار کننده",
        totalCustomers: 0,
        lastPurchase: 0,
        numberOfPurchases: 3000,
        purchaseAmount: 0,
    },
    {
        id: 6,
        section: "نیازمند توجه",
        totalCustomers: 0,
        lastPurchase: 0,
        numberOfPurchases: 200,
        purchaseAmount: 0,
    },
    {
        id: 7,
        section: "خواب آلود",
        totalCustomers: 0,
        lastPurchase: 0,
        numberOfPurchases: 1000,
        purchaseAmount: 0,
    },
    {
        id: 8,
        section: "خواب زمستانی",
        totalCustomers: 0,
        lastPurchase: 0,
        numberOfPurchases: 900,
        purchaseAmount: 0,
    },
    {
        id: 9,
        section: "از دست ندهید",
        totalCustomers: 0,
        lastPurchase: 0,
        numberOfPurchases: 700,
        purchaseAmount: 0,
    },
    {
        id: 10,
        section: "در معرض خطر",
        totalCustomers: 0,
        lastPurchase: 0,
        numberOfPurchases: 1000,
        purchaseAmount: 0,
    },
    {
        id: 11,
        section: "رویگردان",
        totalCustomers: 0,
        lastPurchase: 0,
        numberOfPurchases: 2000,
        purchaseAmount: 0,
    },
    {
        id: 12,
        section: "از دست رفته",
        totalCustomers: 0,
        lastPurchase: 0,
        numberOfPurchases: 750,
        purchaseAmount: 0,
    },
];
